name: express-api

services:
  app:
    build:
      context: ./docker
      dockerfile: dev.node.dockerfile
    container_name: app
    depends_on:
      - db
    environment:
      MONGO_URI: mongodb://josebsx:GWFMgJrTBUgbwtFw@db:27017/
    networks:
      - express-network
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./:/usr/app
  db:
    container_name: db
    environment:
      MONGO_INITDB_ROOT_USERNAME: josebsx
      MONGO_INITDB_ROOT_PASSWORD: GWFMgJrTBUgbwtFw
    image: mongo:latest
    networks:
      - express-network
    ports:
      - '27017:27017'
    restart: always
    volumes:
      - db:/data/db

networks:
  express-network:
    driver: bridge

volumes:
  db:
